/* File Name: showkey.c
 * Author:    Shimin Chen
 *
 * Description: show keys generated by keygen
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <assert.h>
#include <fcntl.h>

#include "keygen.h"

#define NUM_KEY_IN_BUFFER	(1024*1024/sizeof(int))

Int64 key[NUM_KEY_IN_BUFFER];

int main (int argc, char *argv[])
{
	char *filename;

	int fd;
	int i, len, this_num;
  	Int64 keynum;

	// get parameters
	if (argc < 2) {
	  fprintf (stderr, "Usage: %s <file_name>\n", argv[0]);
	  exit (1);
	}
	filename = argv[1];

	// open file for input
	fd = open (filename, 0, 0644);
	if (fd == -1) {
	  perror ("open"); exit (1);
	}

	// read file contents and output
	keynum = 0;
	while ((len = read (fd, key, sizeof(key))) > 0) {
	  assert (len % sizeof(Int64) == 0);
	  this_num = len/sizeof(Int64);

	  for (i=0; i<this_num; i++) {
	     printf ("%016llx\n", key[i]);
	  }

	  keynum += this_num;
	  
	} // end of while
	printf ("Total %lld keys\n", keynum);

	// close file
	close (fd);
	
	return 0;
}
